site_name: Raffaele Pio Ruggiero 
site_url: https://mydomain.org/mysite
theme:
  name: material
  theme:
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      font:
        text: Open Sans
      toggle:
        icon: material/brightness-4
        name: Switch to light mode



    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      accent: orange
      font:
        text: Open Sans
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode


  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

extra_css:
- css/extra.css

plugins:
  - search
  - tags
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption


nav:
  - Home: index.md
  - Code Docs:
    - Python: coding/my-first-code.md
  - About:
      - About Me: about/about.md
      - Childhood: about/childhood.md
  - Blog:
    - blog/index.md